{{- if not .Values.librenms.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librenms.appkeySecretName" . }}
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
type: Opaque
data:
  appkey: {{ include "librenms.appkeyValue" . | b64enc | quote }}
{{- end }}
